### ISSUE TITLE
don't work

### ISSUE THREAD

**Issue by scavru** [Maykeye/hoperator#1]
**hoperator log:**
`(C:\oobabooga_windows\installer_files\env) C:\oobabooga_windows\hoperator>python kai_listener.py --generator oobabooga
 * Serving Flask app 'kai_listener'
 * Debug mode: on
WARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.
 * Running on http://127.0.0.1:11111
Press CTRL+C to quit
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 398-790-759
127.0.0.1 - - [22/Jul/2023 16:53:52] "GET /api/v1/model HTTP/1.1" 200 -
***
hi

127.0.0.1 - - [22/Jul/2023 16:53:57] "POST /api/v1/generate HTTP/1.1" 500 -
Traceback (most recent call last):
  File "C:\oobabooga_windows\installer_files\env\lib\site-packages\urllib3\connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
  File "C:\oobabooga_windows\installer_files\env\lib\site-packages\urllib3\connectionpool.py", line 449, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "C:\oobabooga_windows\installer_files\env\lib\site-packages\urllib3\connectionpool.py", line 444, in _make_request
    httplib_response = conn.getresponse()
  File "C:\oobabooga_windows\installer_files\env\lib\http\client.py", line 1375, in getresponse
    response.begin()
  File "C:\oobabooga_windows\installer_files\env\lib\http\client.py", line 318, in begin
    version, status, reason = self._read_status()
  File "C:\oobabooga_windows\installer_files\env\lib\http\client.py", line 287, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
http.client.RemoteDisconnected: Remote end closed connection without response

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\oobabooga_windows\installer_files\env\lib\site-packages\requests\adapters.py", line 486, in send
    resp = conn.urlopen(
  File "C:\oobabooga_windows\installer_files\env\lib\site-packages\urllib3\connectionpool.py", line 787, in urlopen
    retries = retries.increment(
  File "C:\oobabooga_windows\installer_files\env\lib\site-packages\urllib3\util\retry.py", line 550, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "C:\oobabooga_windows\installer_files\env\lib\site-packages\urllib3\packages\six.py", line 769, in reraise
    raise value.with_traceback(tb)
  File "C:\oobabooga_windows\installer_files\env\lib\site-packages\urllib3\connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
  File "C:\oobabooga_windows\installer_files\env\lib\site-packages\urllib3\connectionpool.py", line 449, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "C:\oobabooga_windows\installer_files\env\lib\site-packages\urllib3\connectionpool.py", line 444, in _make_request
    httplib_response = conn.getresponse()
  File "C:\oobabooga_windows\installer_files\env\lib\http\client.py", line 1375, in getresponse
    response.begin()
  File "C:\oobabooga_windows\installer_files\env\lib\http\client.py", line 318, in begin
    version, status, reason = self._read_status()
  File "C:\oobabooga_windows\installer_files\env\lib\http\client.py", line 287, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
urllib3.exceptions.ProtocolError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\oobabooga_windows\installer_files\env\lib\site-packages\flask\app.py", line 2213, in __call__
    return self.wsgi_app(environ, start_response)
  File "C:\oobabooga_windows\installer_files\env\lib\site-packages\flask\app.py", line 2193, in wsgi_app
    response = self.handle_exception(e)
  File "C:\oobabooga_windows\installer_files\env\lib\site-packages\flask\app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\oobabooga_windows\installer_files\env\lib\site-packages\flask\app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\oobabooga_windows\installer_files\env\lib\site-packages\flask\app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\oobabooga_windows\installer_files\env\lib\site-packages\flask\app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "C:\oobabooga_windows\hoperator\kai_listener.py", line 51, in generate_text
    response = gen.run(new_request)
  File "C:\oobabooga_windows\hoperator\gen_oobabooga.py", line 46, in run
    response = requests.post(f"http://{self.server}:{self.server_port}/run/textgen", json={
  File "C:\oobabooga_windows\installer_files\env\lib\site-packages\requests\api.py", line 115, in post
    return request("post", url, data=data, json=json, **kwargs)
  File "C:\oobabooga_windows\installer_files\env\lib\site-packages\requests\api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
  File "C:\oobabooga_windows\installer_files\env\lib\site-packages\requests\sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\oobabooga_windows\installer_files\env\lib\site-packages\requests\sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
  File "C:\oobabooga_windows\installer_files\env\lib\site-packages\requests\adapters.py", line 501, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
**`
kobold master log**
```
WARNING    | __main__:actionsubmit:4218 - Unknown tokenizer 'hoperator/oobabooga'
Tokens:1, Txt:hi
Exception in thread Thread-34:
Traceback (most recent call last):
  File "B:\python\lib\site-packages\requests\models.py", line 971, in json
    return complexjson.loads(self.text, **kwargs)
  File "B:\python\lib\json\__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "B:\python\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "B:\python\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "B:\python\lib\threading.py", line 932, in _bootstrap_inner
    self.run()
  File "B:\python\lib\threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "B:\python\lib\site-packages\socketio\server.py", line 731, in _handle_event_internal
    r = server._trigger_event(data[0], namespace, sid, *data[1:])
  File "B:\python\lib\site-packages\socketio\server.py", line 756, in _trigger_event
    return self.handlers[namespace][event](*args)
  File "B:\python\lib\site-packages\flask_socketio\__init__.py", line 282, in _handler
    return self._handle_event(handler, message, namespace, sid,
  File "B:\python\lib\site-packages\flask_socketio\__init__.py", line 826, in _handle_event
    ret = handler(*args)
  File "aiserver.py", line 466, in g
    return f(*a, **k)
  File "aiserver.py", line 3612, in get_message
    actionsubmit(msg['data'], actionmode=msg['actionmode'])
  File "aiserver.py", line 4260, in actionsubmit
    calcsubmit(data) # Run the first action through the generator
  File "aiserver.py", line 4747, in calcsubmit
    sendtoapi(utils.decodenewlines(tokenizer.decode(subtxt)), min, max)
  File "aiserver.py", line 5207, in sendtoapi
    js = req.json()
  File "B:\python\lib\site-packages\requests\models.py", line 975, in json
    raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
requests.exceptions.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```
**kobold DEV**
`(C:\oobabooga_windows\installer_files\env) C:\oobabooga_windows\hoperator>python kai_listener.py --generator oobabooga
 * Serving Flask app 'kai_listener'
 * Debug mode: on
WARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.
 * Running on http://127.0.0.1:11111
Press CTRL+C to quit
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 398-790-759
127.0.0.1 - - [22/Jul/2023 17:00:01] "GET /api/v1/model HTTP/1.1" 200 -
***
hi

127.0.0.1 - - [22/Jul/2023 17:00:10] "POST /api/v1/generate HTTP/1.1" 500 -
Traceback (most recent call last):
  File "C:\oobabooga_windows\installer_files\env\lib\site-packages\urllib3\connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
  File "C:\oobabooga_windows\installer_files\env\lib\site-packages\urllib3\connectionpool.py", line 449, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "C:\oobabooga_windows\installer_files\env\lib\site-packages\urllib3\connectionpool.py", line 444, in _make_request
    httplib_response = conn.getresponse()
  File "C:\oobabooga_windows\installer_files\env\lib\http\client.py", line 1375, in getresponse
    response.begin()
  File "C:\oobabooga_windows\installer_files\env\lib\http\client.py", line 318, in begin
    version, status, reason = self._read_status()
  File "C:\oobabooga_windows\installer_files\env\lib\http\client.py", line 287, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
http.client.RemoteDisconnected: Remote end closed connection without response

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\oobabooga_windows\installer_files\env\lib\site-packages\requests\adapters.py", line 486, in send
    resp = conn.urlopen(
  File "C:\oobabooga_windows\installer_files\env\lib\site-packages\urllib3\connectionpool.py", line 787, in urlopen
    retries = retries.increment(
  File "C:\oobabooga_windows\installer_files\env\lib\site-packages\urllib3\util\retry.py", line 550, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "C:\oobabooga_windows\installer_files\env\lib\site-packages\urllib3\packages\six.py", line 769, in reraise
    raise value.with_traceback(tb)
  File "C:\oobabooga_windows\installer_files\env\lib\site-packages\urllib3\connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
  File "C:\oobabooga_windows\installer_files\env\lib\site-packages\urllib3\connectionpool.py", line 449, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "C:\oobabooga_windows\installer_files\env\lib\site-packages\urllib3\connectionpool.py", line 444, in _make_request
    httplib_response = conn.getresponse()
  File "C:\oobabooga_windows\installer_files\env\lib\http\client.py", line 1375, in getresponse
    response.begin()
  File "C:\oobabooga_windows\installer_files\env\lib\http\client.py", line 318, in begin
    version, status, reason = self._read_status()
  File "C:\oobabooga_windows\installer_files\env\lib\http\client.py", line 287, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
urllib3.exceptions.ProtocolError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\oobabooga_windows\installer_files\env\lib\site-packages\flask\app.py", line 2213, in __call__
    return self.wsgi_app(environ, start_response)
  File "C:\oobabooga_windows\installer_files\env\lib\site-packages\flask\app.py", line 2193, in wsgi_app
    response = self.handle_exception(e)
  File "C:\oobabooga_windows\installer_files\env\lib\site-packages\flask\app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\oobabooga_windows\installer_files\env\lib\site-packages\flask\app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\oobabooga_windows\installer_files\env\lib\site-packages\flask\app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\oobabooga_windows\installer_files\env\lib\site-packages\flask\app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "C:\oobabooga_windows\hoperator\kai_listener.py", line 51, in generate_text
    response = gen.run(new_request)
  File "C:\oobabooga_windows\hoperator\gen_oobabooga.py", line 46, in run
    response = requests.post(f"http://{self.server}:{self.server_port}/run/textgen", json={
  File "C:\oobabooga_windows\installer_files\env\lib\site-packages\requests\api.py", line 115, in post
    return request("post", url, data=data, json=json, **kwargs)
  File "C:\oobabooga_windows\installer_files\env\lib\site-packages\requests\api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
  File "C:\oobabooga_windows\installer_files\env\lib\site-packages\requests\sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\oobabooga_windows\installer_files\env\lib\site-packages\requests\sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
  File "C:\oobabooga_windows\installer_files\env\lib\site-packages\requests\adapters.py", line 501, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
`

`PROMPT     @ 2023-07-22 17:00:06 | hi
ERROR      | __main__:generate:3928 - Traceback (most recent call last):
  File "C:\KoboldAI\miniconda3\lib\site-packages\requests\models.py", line 971, in json
    return complexjson.loads(self.text, **kwargs)
  File "C:\KoboldAI\miniconda3\lib\json\__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "C:\KoboldAI\miniconda3\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\KoboldAI\miniconda3\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "aiserver.py", line 3915, in generate
    genout, already_generated = tpool.execute(model.core_generate, txt, found_entries)
  File "C:\KoboldAI\miniconda3\lib\site-packages\eventlet\tpool.py", line 132, in execute
    six.reraise(c, e, tb)
  File "C:\KoboldAI\miniconda3\lib\site-packages\six.py", line 719, in reraise
    raise value
  File "C:\KoboldAI\miniconda3\lib\site-packages\eventlet\tpool.py", line 86, in tworker
    rv = meth(*args, **kwargs)
  File "C:\KoboldAI\modeling\inference_model.py", line 342, in core_generate
    result = self.raw_generate(
  File "C:\KoboldAI\modeling\inference_model.py", line 589, in raw_generate
    result = self._raw_generate(
  File "C:\KoboldAI\modeling\inference_models\api\class.py", line 118, in _raw_generate
    js = req.json()
  File "C:\KoboldAI\miniconda3\lib\site-packages\requests\models.py", line 975, in json
    raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
requests.exceptions.JSONDecodeError: Expecting value: line 1 column 1 (char 0)`

kobold lite don't see API

**Comment by Maykeye** [comment]
* Never tested on windows, might not work with all non-utf8 encodings and \r\n shenanigans
* This was written for forked version of llama.cpp before llama.cpp it changed internal format(twice), so it will not work models models want to work this, llama.cpp has no commands like `.gen$` on its own.
* App is not archived only in case there'll be more projects like llama.cpp/ooba to marry which there aren't now(as ooba already supports llama). I don't use the app, hence won't fix it(unless there will be PRs/patches).

Use oobabooga loaders for llama, it has half dozens of them now all of which are faster than llama.cpp hoperator used.
